Repository PLADI-ALM/PLADI-ALM-Mobile, pull requests merged in 2023-12, with the labels that each got.

#44 Fix/git action
  .github/workflows/main.yml
  ios/Runner.xcodeproj/project.pbxproj
  ios/fastlane/Fastfile
Labels: ⚓️ CI/CD

#49 fix: 달력 내 선택 해제하는 경우 예외 처리
  lib/View/booking/component/custom_range_calendar.dart
  lib/View/booking/screen/booking_resource_screen.dart
Labels: ⛑️ Fix

#50 [PDA-18] fix: 차량 예약 앱바 타이틀 변경
  lib/View/booking/screen/booking_car_screen.dart
Labels: ⛑️ Fix

#51 [PDA-44/feat] 비품 조회
  asset/image/location.svg
  lib/Model/model/equipment/equipment_list_model.dart
  lib/Model/model/equipment/equipment_list_model.g.dart
  lib/Presenter/equipment/equipment_service.dart
  lib/View/common/screen/root_tab.dart
  lib/View/equipment/component/equipment_cell.dart
  lib/View/equipment/screen/equipment_screen.dart
Labels: 🔮 Feat

#53 fix, feat: 장비/차량 예약 내 선택일시 버그, 예약 내역 아이템 세부 화면 연결
  lib/Model/model/booking/car_model.dart
  lib/Model/model/booking/car_model.g.dart
  lib/Model/model/booking/office_model.dart
  lib/Model/model/booking/office_model.g.dart
  lib/Model/model/booking/resource_model.dart
  lib/Model/model/booking/resource_model.g.dart
  lib/View/booking/component/booking_item_card.dart
  lib/View/booking/component/custom_range_calendar.dart
  lib/View/booking/screen/booking_car_screen.dart
  lib/View/booking/screen/booking_history_screen.dart
  lib/View/booking/screen/booking_resource_screen.dart
  lib/View/booking/screen/general_detail_screen.dart
Labels: ⛑️ Fix, 🔮 Feat
